# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
################################################
# 勿动
deploy:
      type: git
      message: update
      repo:
        s1: git@122.51.68.204:repo/blog.git,master
#######################################################################

# 1、网站
title: Rui's Blog # 网站标题
subtitle: 这个世界最可怕的事，是比你聪明的人，还比你更努力！ # 网站副标题
description: Rui's blog # 网站描述(主要用于SEO，告诉搜索引擎一个关于您站点的简单描述，通常建议在其中包含您网站的关键词。)
author: Rui # 您的名字
language: # 网站使用的语言
timezone: # 网站时区(Hexo 默认使用您电脑的时区。时区列表。比如说：America/New_York, Japan, 和 UTC )
################################################

# 2、网址
url: //ruidada.info # 网址
root: / # 网站根目录
permalink: :year/:month/:day/:title/ # 文章的 永久链接(:year/:month/:day/:title/）
permalink_defaults: # 永久链接中各部分的默认值
################################################

# 3、目录
source_dir: source # 资源文件夹，这个文件夹用来存放内容。
public_dir: public # 公共文件夹，这个文件夹用于存放生成的站点文件。
tag_dir: tags # 标签文件夹
archive_dir: archives # 归档文件夹
category_dir: categories # 分类文件夹
code_dir: downloads/code # Include code 文件夹
i18n_dir: :lang # 国际化（i18n）文件夹
skip_render: # 跳过指定文件的渲染，您可使用 glob 表达式来匹配路径。
################################################

# 4、文章
new_post_name: :title.md # 新文章的文件名称
default_layout: post # 预设布局
titlecase: false # 把标题转换为 title case
external_link: true # 在新标签中打开链接
filename_case: 0 # 把文件名称转换为 (1) 小写或 (2) 大写
render_drafts: false # 显示草稿
post_asset_folder: true # 启动 Asset 文件夹
relative_link: false # 把链接改为与根目录的相对位址
future: true # 显示未来的文章
highlight: # 代码块的设置
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
# PS:默认情况下，Hexo生成的超链接都是绝对地址。例如，如果您的网站域名为example.com,您有一篇文章名为hello，那么绝对链接可能像这样：http://example.com/hello.html，它是绝对于域名的。相对链接像这样：/hello.html，也就是说，无论用什么域名访问该站点，都没有关系，这在进行反向代理时可能用到。通常情况下，建议使用绝对地址。

################################################

# 5、分类&标签
default_category: uncategorized # 默认分类
category_map: # 分类别名
tag_map: # 标签别名
################################################

# 6、日期/时间格式
date_format: YYYY-MM-DD # 日期格式
time_format: HH:mm:ss # 时间格式
################################################

# 7、分页
per_page: 10 # 每页显示的文章量 (0 = 关闭分页功能)
pagination_dir: page # 分页目录
################################################
theme: yilia


jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: true
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
# index_generator:
#   path: ''
#   per_page: 10
#   order_by: -date
  


